branches:
  except: /^v\d/
language: node_js
node_js: node
matrix:
  include:
  - before_install: curl --silent --show-error --location https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/bin '*/stack'
    cache:
      directories: ~/.stack
    after_script: node_modules/.bin/nyc report | npx coveralls
  - os: windows
    env: STACK_ROOT=C:\\s
    cache:
      directories: C:\s
    before_install: choco install haskell-stack
    script: node test.js
