dist: trusty
branches:
  except: /^v\d/
language: node_js
node_js: node
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --resolver=lts-8.11 setup
after_script:
  - npm install coveralls
  - ./node_modules/.bin/nyc report --reporter=text-lcov | coveralls
cache:
  directories: $HOME/.stack
