branches:
  except: /^v\d/
language: node_js
node_js: node
before_install: curl -sSL https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/bin '*/stack'
after_script: node_modules/.bin/nyc report | npx coveralls
cache:
  directories: ~/.stack
